{% set version = "0.12.0" %}

package:
  name: anaconda-project
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/anaconda-project/archive/v{{ version }}.tar.gz
  sha256: 2247b120171cdf5210dcebdc23c4b622e89ff9543908766f799b362761b81a34

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - anaconda-project = anaconda_project.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - anaconda-client
    - conda-pack
    - jinja2
    - python
    - requests
    - ruamel.yaml >=0.15
    - tornado >=4.2
    - tqdm

test:
  requires:
    - pip
    - conda
  imports:
    - anaconda_project
  commands:
    - pip check
    - echo "First of test commands"
    - anaconda-project --help
    - anaconda-project --version
    - echo "Last of test commands"

about:
  home: https://github.com/Anaconda-Platform/anaconda-project
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tool for encapsulating, running, and reproducing data science projects
  description: |
    By adding an anaconda-project.yml to a project directory, a single
    anaconda-project runcommand will be able to set up all dependencies
    and then launch the project.
  doc_url: https://anaconda-project.readthedocs.io
  dev_url: https://github.com/Anaconda-Platform/anaconda-project

extra:
  recipe-maintainers:
    - fpliger
    - goanpeca
    - mingwandroid
    - bollwyvl
